# This workflow will build a golang project for Linux, Windows, and macOS

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.20']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          go build -v -o proxy-agent.exe ./...
        else
          go build -v -o proxy-agent ./...
        fi

    - name: Test
      run: go test -v ./...

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: proxy-agent-${{ matrix.os }}
        path: |
          proxy-agent*
